### ISSUE TITLE
KDE Probability of no onset being calculated across all regions

### ISSUE THREAD

**Issue by nickreich** [reichlab/2017-2018-cdc-flu-contest#17]
Not sure if this is intentional, but pretty sure that the code at https://github.com/reichlab/2017-2018-cdc-flu-contest/blob/c06d0180a86f30b43d0f87d5d4e9c77bf7a4a267/R/kde-utils.R#L134 is calculating, across all regions, the probability of having no onset, when this is fitting a model for a single region. @elray1 was this an intentional decision?

**Comment by nickreich** [comment]
If not intentional, then we can should the loop over regions in kde-utils.R.

**Comment by elray1** [comment]
This is intentional, some regions had no seasons without onset in training, but since there were few training seasons an estimate of zero probability for a given region is unwarranted.  The idea was that pooling regions would give a larger sample size for estimating probability of no onset.

**Comment by nickreich** [comment]
Thought that might be the case. Thanks for confirming the intent!
